<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container85BOW9M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container85BOW9M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container85BOW9M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container85BOW9M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container85BOW9M\App_KernelDevDebugContainer([
    'container.build_hash' => '85BOW9M',
    'container.build_id' => 'b061652d',
    'container.build_time' => 1686063896,
], __DIR__.\DIRECTORY_SEPARATOR.'Container85BOW9M');
