<?php

namespace Container85BOW9M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HvKkh26Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HvKkh26' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HvKkh26'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\CustomersRepository', 'getCustomersRepositoryService', true],
        ], [
            'customerRepository' => 'App\\Repository\\CustomersRepository',
        ]);
    }
}
