<?php

namespace Container85BOW9M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UEaQkNfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UEaQkNf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UEaQkNf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repositoryAddress' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
        ], [
            'repositoryAddress' => 'App\\Repository\\AddressRepository',
        ]);
    }
}
